services:
    hmac_annotation_driver:
        class: HMACBundle\Annotations\Driver\AnnotationDriver
        tags:
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}
            - {name: kernel.event_listener, event: kernel.response, method: onKernelResponse}
            - {name: kernel.event_listener, event: kernel.view, method: onKernelView}
        arguments: [@annotation_reader, "@doctrine.orm.entity_manager", "%hmac.hmac%"]
    HMAC_apiuser_service:
        class: HMACBundle\Services\ApiUserService
        arguments: ["@doctrine.orm.default_entity_manager", "%hmac.hmac_roles%"]